name = "elliesbang_class"
compatibility_date = "2025-10-25"

[build]
command = "npm run build"
cwd = "."  # 그대로 유지

[pages]
pages_build_output_dir = "dist"   # ✅ ./dist 대신 dist 로 변경
functions = "../functions"        # ✅ 상대경로 유지 (루트의 functions 폴더)

[[d1_databases]]
binding = "DB"
database_name = "elliesbang_class"
database_id = "2a518bb3-9a4f-437e-a740-79a6ae96ead5"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "elliesbang_class"
database_id = "2a518bb3-9a4f-437e-a740-79a6ae96ead5"
